#!/bin/bash
source common_vars.sh

echo "Creating build directory and cache directory"

rm -rf $replica_cache_folder
mkdir $replica_cache_folder

echo "Copying source code"

# Upload the http-server source code.
while IFS= read -r ip_address || [[ -n "$ip_address" ]]; do

    ssh -i $keyfile $username@$ip_address rm -rf $replica_build_path
    ssh -i $keyfile $username@$ip_address mkdir -p $replica_build_path

    ssh -i $keyfile $username@$ip_address mkdir $replica_build_path/$replica_cache_folder

    for file in "${replica_source_files[@]}"; do
        echo "Copying $file to $ip_address"
        scp -i $keyfile -r $file $username@$ip_address:$replica_build_path
    done
    echo "Copied http-server source code to : $ip_address"
done < "$replica_file"



# Upload the dns-server source code.
while IFS= read -r ip_address || [[ -n "$ip_address" ]]; do

    ssh -i $keyfile $username@$ip_address rm -rf $dns_build_path
    ssh -i $keyfile $username@$ip_address mkdir -p $dns_build_path

    for file in "${dns_source_files[@]}"; do
        echo "Copying $file to $ip_address"
        scp -i $keyfile -r $file $username@$ip_address:$dns_build_path
    done
    echo "Copied dns-server source code to : $ip_address"

done < "$dns_file"
