#!/bin/bash
source common_vars.sh

printf "Creating build directory and cache directory\n"

rm -rf $replica_cache_folder
mkdir $replica_cache_folder

printf "Copying source code\n\n"

# Upload the http-server source code.
for ip_address in $(cat $replica_file)
do

    if [[ -z "$ip_address" ]]; then
      continue
    fi

    printf "Creating replica build directory in $ip_address\n"

    until ssh -o "StrictHostKeyChecking no" -i  $keyfile $username@$ip_address rm -rf $replica_build_path ; do
      sleep 1
    done

    until ssh -o "StrictHostKeyChecking no" -i $keyfile $username@$ip_address mkdir -p $replica_build_path ; do
      sleep 1
    done

    until ssh -o "StrictHostKeyChecking no" -i $keyfile $username@$ip_address mkdir $replica_build_path/$replica_cache_folder ; do
      sleep 1
    done

    for file in "${replica_source_files[@]}"; do
        printf "Copying $file to $ip_address\n"
        until scp -o "StrictHostKeyChecking no" -i $keyfile -r $file $username@$ip_address:$replica_build_path ; do
          sleep 1
        done
    done
    printf "Copied http-server source code to : $ip_address\n\n"
done

# Upload the dns-server source code.
for ip_address in $(cat $dns_file)
do

    if [[ -z "$ip_address" ]]; then
      continue
    fi

    printf "Creating dns build directory in $ip_address\n"

    until ssh -o "StrictHostKeyChecking no" -i $keyfile $username@$ip_address rm -rf $dns_build_path ; do
      sleep 1
    done

    until ssh -o "StrictHostKeyChecking no" -i $keyfile $username@$ip_address mkdir -p $dns_build_path ; do
      sleep 1
    done

    for file in "${dns_source_files[@]}"; do
        printf "Copying $file to $ip_address\n"
        until scp -o "StrictHostKeyChecking no" -i $keyfile -r $file $username@$ip_address:$dns_build_path ; do
          sleep 1
        done
    done
    printf "Copied dns-server source code to : $ip_address\n\n"

done
