#!/bin/bash
source common_vars.sh

echo "Creating build directory and cache directory"

rm -rf $replica_cache_folder
mkdir $replica_cache_folder

echo "Copying source code"

# Upload the http-server source code.
for ip_address in $(cat $replica_file)
do

    if [[ -z "$ip_address" ]]; then
      continue
    fi

    ssh -o "StrictHostKeyChecking no" -i  $keyfile $username@$ip_address rm -rf $replica_build_path
    ssh -o "StrictHostKeyChecking no" -i $keyfile $username@$ip_address mkdir -p $replica_build_path

    ssh -o "StrictHostKeyChecking no" -i $keyfile $username@$ip_address mkdir $replica_build_path/$replica_cache_folder

    for file in "${replica_source_files[@]}"; do
        echo "Copying $file to $ip_address"
        scp -o "StrictHostKeyChecking no" -i $keyfile -r $file $username@$ip_address:$replica_build_path
    done
    echo "Copied http-server source code to : $ip_address"
done

# Upload the dns-server source code.
for ip_address in $(cat $dns_file)
do

    if [[ -z "$ip_address" ]]; then
      continue
    fi

    ssh -o "StrictHostKeyChecking no" -i $keyfile $username@$ip_address rm -rf $dns_build_path
    ssh -o "StrictHostKeyChecking no" -i $keyfile $username@$ip_address mkdir -p $dns_build_path

    for file in "${dns_source_files[@]}"; do
        echo "Copying $file to $ip_address"
        scp -o "StrictHostKeyChecking no" -i $keyfile -r $file $username@$ip_address:$dns_build_path
    done
    echo "Copied dns-server source code to : $ip_address"

done
