#!/usr/bin/env python3
from dnslib.server import DNSLogger, DNSServer
import argparse
import os

from dns.dns_server import DNSResolver
from dns.geo_ip_locator import GeoIPLocator

parser = argparse.ArgumentParser()
parser.add_argument("-p", default=40002)
parser.add_argument("-n", default="cs5700cdnorigin.ccs.neu.edu")
args = parser.parse_args()
port = int(args.p)
name = args.n

abspath = os.path.abspath(__file__)
dname = os.path.dirname(abspath)
os.chdir(dname)
geo_ip_locator = GeoIPLocator("./http-repls.txt")

# Start the server to run infinitely, using the resolver designed above
if __name__ == "__main__":
    resolver = DNSResolver(geo_ip_locator, name)
    logger = DNSLogger(prefix=False)
    server = DNSServer(resolver, port=port, logger=logger)
    server.start()
