#!/usr/bin/env python3
import argparse

from replica.http_server import ReplicaServer
import os

# Change the script path to current directory.
abspath = os.path.abspath(__file__)
dname = os.path.dirname(abspath)
os.chdir(dname)

if __name__ == "__main__":
    # Parse command line arguments to get port and origin.
    args_parser = argparse.ArgumentParser()
    args_parser.add_argument("-p", type=int)
    args_parser.add_argument("-o", type=str)
    args_parser.parse_args()

    args = args_parser.parse_args()

    # Create an instance of http server to receive request on the replica.
    replica_server = ReplicaServer(args.p, args.o)

    # Start http server.
    replica_server.start_http_server()
