#!/bin/bash
source common_vars.sh

# Run the http server
for ip_address in $(cat $replica_file)
do
    if [[ -z "$ip_address" ]]; then
      continue
    fi

    printf "Running http-server on : $ip_address\n"

    until ssh -o "StrictHostKeyChecking no" -i $keyfile $username@$ip_address chmod +x $replica_build_path/httpserver;
    do
        sleep 1
    done

    until ssh -o "StrictHostKeyChecking no" -i $keyfile $username@$ip_address nohup $replica_build_path/httpserver -p $port -o $origin > /dev/null 2>/dev/null &
    do
        sleep 1
    done

    printf "Ran http-server on : $ip_address\n\n"
done

# Run the dns server
for ip_address in $(cat $dns_file)
do
    if [[ -z "$ip_address" ]]; then
      continue
    fi

    printf "Running dns-server on : $ip_address\n"

    until ssh -o "StrictHostKeyChecking no" -i $keyfile $username@$ip_address chmod +x $dns_build_path/dnsserver;
    do
        sleep 1
    done

    until ssh -o "StrictHostKeyChecking no" -i $keyfile $username@$ip_address nohup $dns_build_path/dnsserver -p $port -n $name > /dev/null 2>/dev/null &
    do
        sleep 1
    done

    printf "Ran dns-server on : $ip_address\n\n"
done