#!/bin/bash
source common_vars.sh

for ip_address in $(cat $replica_file)
do
    if [[ -z "$ip_address" ]]; then
      continue
    fi
    printf "Stopping http-server on : $ip_address\n"

    until ssh -o "StrictHostKeyChecking no" -i $keyfile $username@$ip_address pkill python -u $username || true;
    do
        sleep 1
    done
    printf "Stopped http-server on : $ip_address\n\n"
done


for ip_address in $(cat $dns_file)
do
    if [[ -z "$ip_address" ]]; then
      continue
    fi

    printf "Stopping dns-server on : $ip_address\n"

    until ssh -o "StrictHostKeyChecking no" -i $keyfile $username@$ip_address pkill python -u $username || true ;
    do
        sleep 1
    done
    printf "Stopped dns-server on : $ip_address\n\n"
done

