#!/bin/bash
source common_vars.sh

for ip_address in $(cat $replica_file)
do
    if [[ -z "$ip_address" ]]; then
      continue
    fi

    ssh -o "StrictHostKeyChecking no" -i $keyfile $username@$ip_address pkill python -u $username
    echo "Stopped http-server on : $ip_address"
done


for ip_address in $(cat $dns_file)
do
    if [[ -z "$ip_address" ]]; then
      continue
    fi

    ssh -o "StrictHostKeyChecking no" -i $keyfile $username@$ip_address pkill python -u $username
    echo "Stopped dns-server on : $ip_address"
done

